package dev.rodrigo.liveupdates;

import android.Manifest; import android.app.*; import android.content.*; import android.content.pm.PackageManager; import android.os.*; import android.widget.*; import androidx.activity.ComponentActivity; import androidx.activity.result.ActivityResultLauncher; import androidx.activity.result.contract.ActivityResultContracts; import androidx.core.app.*; import androidx.core.content.ContextCompat;

public class MainActivity extends ComponentActivity {
 private static final String CHANNEL="journey", NAME="Live journey", ID=42+""; private static final int NOTIFICATION_ID=42; private final Handler handler=new Handler(Looper.getMainLooper()); private TextView status; private int progress; private boolean running;
 private final ActivityResultLauncher<String> permission=registerForActivityResult(new ActivityResultContracts.RequestPermission(),granted->{if(granted)startJourney();else status.setText("Notification permission denied");});
 private final Runnable tick=new Runnable(){@Override public void run(){if(!running)return;progress=Math.min(100,progress+10);if(progress>=100){finishJourney();return;}postLive();handler.postDelayed(this,2000);}};
 @Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);status=findViewById(R.id.status);createChannel();findViewById(R.id.start).setOnClickListener(v->requestAndStart());findViewById(R.id.cancel).setOnClickListener(v->cancelJourney());status.setText("Ready. Start the simulated delivery yourself to create a Live Update candidate.");}
 private void createChannel(){NotificationManager nm=getSystemService(NotificationManager.class);if(Build.VERSION.SDK_INT>=26)nm.createNotificationChannel(new NotificationChannel(CHANNEL,NAME,NotificationManager.IMPORTANCE_DEFAULT));}
 private void requestAndStart(){if(Build.VERSION.SDK_INT>=33&&ContextCompat.checkSelfPermission(this,Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED){permission.launch(Manifest.permission.POST_NOTIFICATIONS);return;}startJourney();}
 private void startJourney(){progress=0;running=true;postLive();handler.removeCallbacks(tick);handler.postDelayed(tick,2000);status.setText("Simulated journey started");}
 private void postLive(){NotificationCompat.ProgressStyle style=new NotificationCompat.ProgressStyle().addProgressSegment(new NotificationCompat.ProgressStyle.Segment(35).setId(1)).addProgressSegment(new NotificationCompat.ProgressStyle.Segment(65).setId(2)).addProgressPoint(new NotificationCompat.ProgressStyle.Point(35).setId(10)).setProgress(progress).setStyledByProgress(true);Intent open=new Intent(this,MainActivity.class);PendingIntent pi=PendingIntent.getActivity(this,0,open,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);NotificationCompat.Builder b=new NotificationCompat.Builder(this,CHANNEL).setSmallIcon(R.drawable.ic_status).setContentTitle("Delivery in progress").setContentText("Journey progress: "+progress+"%").setContentIntent(pi).setOnlyAlertOnce(true).setOngoing(true).setRequestPromotedOngoing(true).setStyle(style).setProgress(100,progress,false);if(Build.VERSION.SDK_INT>=36)b.setShortCriticalText(progress+"%");try{NotificationManagerCompat.from(this).notify(NOTIFICATION_ID,b.build());status.setText("Live Update candidate posted: "+progress+"%");}catch(SecurityException e){status.setText("Cannot post notification: "+e.getMessage());}}
 private void finishJourney(){running=false;handler.removeCallbacks(tick);NotificationCompat.Builder b=new NotificationCompat.Builder(this,CHANNEL).setSmallIcon(R.drawable.ic_status).setContentTitle("Delivery complete").setContentText("The simulated journey reached 100%.").setOngoing(false).setAutoCancel(true);try{NotificationManagerCompat.from(this).notify(NOTIFICATION_ID,b.build());}catch(SecurityException ignored){}status.setText("Journey complete; Live Update ended");}
 private void cancelJourney(){running=false;handler.removeCallbacks(tick);NotificationManagerCompat.from(this).cancel(NOTIFICATION_ID);status.setText("Journey cancelled and notification removed");}
 @Override protected void onDestroy(){handler.removeCallbacksAndMessages(null);super.onDestroy();}
}