package gal.rodrigosambade.liveupdatelab;
import android.Manifest;import android.app.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.os.*;import android.widget.*;import androidx.activity.result.*;import androidx.activity.result.contract.ActivityResultContracts;import androidx.appcompat.app.AppCompatActivity;import androidx.core.content.ContextCompat;
public class MainActivity extends AppCompatActivity{
 static final String CHANNEL="journey";static final int ID=7;Handler h=new Handler(Looper.getMainLooper());TextView status;ProgressBar bar;int progress;boolean running;NotificationManager nm;ActivityResultLauncher<String> permission=registerForActivityResult(new ActivityResultContracts.RequestPermission(),ok->{if(ok)startJourney();else status.setText("Sin permiso de notificaciones");});
 protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);status=findViewById(R.id.status);bar=findViewById(R.id.progress);nm=getSystemService(NotificationManager.class);createChannel();findViewById(R.id.start).setOnClickListener(v->ensureAndStart());findViewById(R.id.stop).setOnClickListener(v->stopJourney());}
 void createChannel(){if(Build.VERSION.SDK_INT>=26)nm.createNotificationChannel(new NotificationChannel(CHANNEL,"Trayectos activos",NotificationManager.IMPORTANCE_LOW));}
 void ensureAndStart(){if(Build.VERSION.SDK_INT>=33&&ContextCompat.checkSelfPermission(this,Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)permission.launch(Manifest.permission.POST_NOTIFICATIONS);else startJourney();}
 void startJourney(){h.removeCallbacksAndMessages(null);progress=0;running=true;tick();}
 void tick(){if(!running)return;bar.setProgress(progress);status.setText("Trayecto: "+progress+"%");post(progress);if(progress>=100){running=false;status.setText("Trayecto completado");h.postDelayed(()->nm.cancel(ID),5000);return;}progress=Math.min(100,progress+5);h.postDelayed(this::tick,1000);}
 void post(int p){Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,CHANNEL):new Notification.Builder(this);b.setSmallIcon(R.drawable.ic_lab).setContentTitle("Repartidor en camino").setContentText(p<100?"Progreso del trayecto: "+p+"%":"Entrega completada").setOnlyAlertOnce(true).setOngoing(p<100).setShowWhen(false);if(Build.VERSION.SDK_INT>=36){Notification.ProgressStyle s=new Notification.ProgressStyle().setProgress(p).setStyledByProgress(true).addProgressSegment(new Notification.ProgressStyle.Segment(35).setColor(Color.rgb(66,133,244))).addProgressSegment(new Notification.ProgressStyle.Segment(35).setColor(Color.rgb(52,168,83))).addProgressSegment(new Notification.ProgressStyle.Segment(30).setColor(Color.rgb(251,188,4))).addProgressPoint(new Notification.ProgressStyle.Point(35).setColor(Color.DKGRAY)).addProgressPoint(new Notification.ProgressStyle.Point(70).setColor(Color.DKGRAY));b.setStyle(s);Bundle extras=new Bundle();extras.putBoolean("android.requestPromotedOngoing",true);extras.putString("android.shortCriticalText",p+"%");b.addExtras(extras);}else b.setProgress(100,p,false);nm.notify(ID,b.build());}
 void stopJourney(){running=false;h.removeCallbacksAndMessages(null);nm.cancel(ID);status.setText("Trayecto cancelado");}
 protected void onDestroy(){h.removeCallbacksAndMessages(null);super.onDestroy();}
}
